post->comments are now nicely iterable. alos alot of other yummy updates and fixes

diff --git a/gitblog/skeleton/hooks/post-commit b/gitblog/skeleton/hooks/post-commit
--- a/gitblog/skeleton/hooks/post-commit
+++ b/gitblog/skeleton/hooks/post-commit
@@ -1,7 +1,7 @@
 #!/bin/sh
 cd $(dirname "$0")
 SECRET=$(grep 'gb::$secret' ../../../gb-config.php | cut -d' ' -f 3 | sed "s/[;']//g")
-git --git-dir=.. --work-tree=../.. log -p --full-index -1 \
+RSP=$(git --git-dir=.. --work-tree=../.. log -p --full-index -1 \
 | curl \
 	-H 'x-gb-shared-secret: '$SECRET \
 	--connect-timeout 5 \
@@ -9,4 +9,8 @@ git --git-dir=.. --work-tree=../.. log -p --full-index -1 \
 	--silent --show-error \
 	--data-binary @- \
 	-k \
-	$(cat ../info/gitblog-site-url)'gitblog/hooks/post-patch.php'
+	$(cat ../info/gitblog-site-url)'gitblog/hooks/post-patch.php')
+echo "$RSP"
+if (echo "$RSP" | grep -q -E '^error'); then
+	exit 1
+fi
